name: trello_attach_PR

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  attach-trello:
    runs-on: ubuntu-latest
    name: Find trello link and attach to card
    steps:
      - uses: persononomo/trello_actions/attach_to_trello-card-action@master
        with:
          trello-key: ${{ secrets.TRELLO_KEY }}
          trello-token: ${{ secrets.TRELLO_TOKEN }}
          repo-token: ${{ secrets.OVERSECURED_GITHUB_TOKEN }}

          ## optional
          # add-pr-comment: true
          ## required if add-pr-comment is true.  secrets.GITHUB_TOKEN is supplied by GH action implicitly.
